services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9081:9080"
      - "9090:9090"
    restart: unless-stopped
    tty: true
    stdin_open: true
    command: sh -c "(sleep 3; echo '+ giper/baza/app/run port=9090'; cat) | npm start"

    # http://localhost:9081/bog/wiki/app/-/test.html
