name: Tauri Desktop Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-desktop:
    uses: b-on-g/tauri-mol-workflow-template/.github/workflows/tauri_reusable.yml@master
    with:
      mam_module_path: bog/wiki/app
      mam_dev_port: '9080'
      tauri_config: bog/wiki/src-tauri/tauri.conf.json
      checkout_path: bog/wiki
    secrets: inherit
